services:
  db:
    image: postgres:latest
    container_name: molt_pedidos_db
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ../data/postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'log_timezone=America/Bogota' -c 'timezone=America/Bogota'"
  api:
    build: .
    container_name: molt_pedidos_api
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env
    volumes:
      - .:/code
    ports:
      - "4000:8000"
    depends_on:
      - db
